language: node_js
cache:
  directories:
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
script:
  - npm run postinstall
deploy:
  provider: heroku
  api_key: fe28b69f-0ba7-4ac1-a11e-9b90ea560f4d
app:
  master: topcodermobile